### ISSUE TITLE
Please add a new study type: "transport infrastructure screening"

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/csis#118]
We need a new set of the templates for the future "transport infrastructure screening" study type. Not sure which steps, so for now just do a copy of everything we have in the urban screening.

**Comment by DenoBeno** [comment]
I have added a new study type https://csis.myclimateservice.eu/taxonomy/study-type/screening-transport

At the moment, this is an exact copy of the urban screening study - please start editing the study description and the individual steps ASAP. If nothing else, then just change the descriptions, rename and/or and remove the steps that aren't needed in this study type.

**Comment by patrickkaleta** [comment]
> I have added a new study type https://csis.myclimateservice.eu/taxonomy/study-type/screening-transport
> 
> At the moment, this is an exact copy of the urban screening study - please start editing the study description and the individual steps ASAP. If nothing else, then just change the descriptions, rename and/or and remove the steps that aren't needed in this study type.

I can take care of the actual implementation/configuration in the CSIS. 

But somebody needs to provide me with the necessary details (study type description, individual steps and their order), since I have no knowledge of that. 
**Who could do that?** @luis-meteogrid ? @ghilbrae ?

**Comment by ghilbrae** [comment]
We are going through the study templates to asses what might need to be changed/removed. 

Concerning the workflow for the steps, the study will follow those defined in the mockups that can be found: https://newrepository.atosresearch.eu/index.php/f/127444

_____________________

**HOME**

Advanced Screening: Transport Infrastructure
study_type_id
study-type:screening-transport
TODO: change this description

> The objective of this demonstration case is to improve the resilience of existing transport infrastructure, through the development of climate-proofing infrastructure and facilitate the planning and management of maintenance tasks on the Spanish ground transport networks thanks to the development of indicators that contribute to their operation safety, profitability and sustainability in both the short and long term. The results of this demonstration case will help managers, whether they are public administration or licensed companies, to the efficient and cost-effective planning of resources and budget for the design and implementation of climate-driven impacts adaptation measures in the Spanish highway networks. 
> 
> This study type triggers the screening process that estimates the impact of the considered hazards on road elements and road traffic. A key difference between this study and those related to urban infrastructure is the highly specialized knowledge of the user that will make use of the study, likely an engineer. This will result on having a characterization of both vulnerability and exposition done by an expert based on their own experience. Lastly, the impact of Climate Change over the element at risk will be determined based on the information submitted to the system.

Study calculation
EMIKAT screening [1]

Following "screening" calculations are performed for the study area:
Climate Change impact over each road element depending on hazard, vulnerability and exposition.
Hazards taken into account are:
- Extreme precipitation events
- Windstoms
- Heat waves
- Snow and ice
- Forest fires

Some of these calculations are triggered whenever a study area is changed. Please be patient, it can take 15-30 min for these initial calculations to finish.

[1] @patrickkaleta this may have two options. Our study can either be calculated by our own tool, the one that will be also embedded in the CSIS but also by EMIKAT.

_________________________________

We will continue working on the other templates and will add more comments to address them.

**Comment by ghilbrae** [comment]
How do we proceed to test the integration with our application? Let's say for the exposition template, for example.

**Comment by patrickkaleta** [comment]
@ghilbrae 
I configured the workflow of the steps according to the mockup you mentioned (I only had to remove the EEA factsheet step). I removed that step in the template for the "Transport Infrastructure" study type, as well as in the (currently only) study of that type - Study 55.
Also, I changed the description of this study type to what you posted in your comment above, though I'm not sure if you want

> Following "screening" calculations are performed for the study area:
Climate Change impact over each road element depending on hazard, vulnerability and exposition.
Hazards taken into account are:
>
> - Extreme precipitation events
> - Windstoms
> - Heat waves
> - Snow and ice
> - Forest fires
>
> Some of these calculations are triggered whenever a study area is changed. Please be patient, it can take 15-30 min for these initial calculations to finish.

also to be part of the description or not. Also, keep in mind that this is the general description for this study type, so I'm not sure that we should include phrases like "...objective of this demonstration case...", since to me that sounds more like a description of a specific study of that study type.

> Study calculation
EMIKAT screening [1]
...
> [1] @patrickkaleta this may have two options. Our study can either be calculated by our own tool, the one that will be also embedded in the CSIS but also by EMIKAT.

TBH, I don't know how exactly we want to handle multiple calculation methods in the future (will it automatically be calculated with all the methods? Will the user have an option to select one? ...), but for now we only support one calculation type, so for now we leave it at "Emikat screening".

**Comment by patrickkaleta** [comment]
### Just FYI:

- Study types and their templates can be viewed and configured [here](https://csis.myclimateservice.eu/admin/structure/taxonomy/manage/study_type/overview), **but changes in the template will not affect already existing studies of that type!**
- for that the individual studies need to be updated 
   - either by changing to a different study type first and then back to the original one -> this resets the study
  - or by just editing the individual group or its GL-steps
- to get an overview of existing studies, you can go [here](https://csis.myclimateservice.eu/maintenance/studies/). There you can also filter for a certain study type

I'll try to implement a feature, which would list all the GL-steps of a study, so that it becomes easier to update existing GL-steps. This should be easy to accomplish with a View in Drupal.

**Comment by ghilbrae** [comment]
> I configured the workflow of the steps according to the mockup you mentioned (I only had to remove the EEA factsheet step). I removed that step in the template for the "Transport Infrastructure" study type, as well as in the (currently only) study of that type - Study 55.
> Also, I changed the description of this study type to what you posted in your comment above, though I'm not sure if you want
> 
> > Following "screening" calculations are performed for the study area:
> > Climate Change impact over each road element depending on hazard, vulnerability and exposition.
> > Hazards taken into account are:
> > 
> > * Extreme precipitation events
> > * Windstoms
> > * Heat waves
> > * Snow and ice
> > * Forest fires
> > 
> > Some of these calculations are triggered whenever a study area is changed. Please be patient, it can take 15-30 min for these initial calculations to finish.
> 
For this we took as an example what was there for the general type of study but I agree that it may be too much for the study.

> also to be part of the description or not. Also, keep in mind that this is the general description for this study type, so I'm not sure that we should include phrases like "...objective of this demonstration case...", since to me that sounds more like a description of a specific study of that study type.
> 
Sure, no need to put that in there.

> > Study calculation
> > EMIKAT screening [1]
> > ...
> > [1] @patrickkaleta this may have two options. Our study can either be calculated by our own tool, the one that will be also embedded in the CSIS but also by EMIKAT.
> 
> TBH, I don't know how exactly we want to handle multiple calculation methods in the future (will it automatically be calculated with all the methods? Will the user have an option to select one? ...), but for now we only support one calculation type, so for now we leave it at "Emikat screening".

OK, then we will leave as it is and see how we can send the results calculated on our application to the CSIS.

**Comment by patrickkaleta** [comment]
> > I configured the workflow of the steps according to the mockup you mentioned (I only had to remove the EEA factsheet step). I removed that step in the template for the "Transport Infrastructure" study type, as well as in the (currently only) study of that type - Study 55.
> > Also, I changed the description of this study type to what you posted in your comment above, though I'm not sure if you want
> > > Following "screening" calculations are performed for the study area:
> > > Climate Change impact over each road element depending on hazard, vulnerability and exposition.
> > > Hazards taken into account are:
> > > 
> > > * Extreme precipitation events
> > > * Windstoms
> > > * Heat waves
> > > * Snow and ice
> > > * Forest fires
> > > 
> > > Some of these calculations are triggered whenever a study area is changed. Please be patient, it can take 15-30 min for these initial calculations to finish.
> 
> For this we took as an example what was there for the general type of study but I agree that it may be too much for the study.

No, I don't necessarily think it would be too much. I just wasn't sure whether you wanted it to be part of the description. I will include it and instead remove the part with the "demonstration case" in the first sentence. Feel free to check and adapt the description as you wish.

**Comment by patrickkaleta** [comment]
> How do we proceed to test the integration with our application? Let's say for the exposition template, for example.

This is further addressed in this issue #122

**Comment by p-a-s-c-a-l** [comment]
Done? Can we close this issue?

**Comment by patrickkaleta** [comment]
@DenoBeno mentioned to me that there is still something to be done here and that I should assist Meteogrid for that. 

So a question to @ghilbrae, is that correct or was Denis rather thinking about #122? From my point of view the new study type is ready and available in CSIS and no more configuration is needed, so I would close this issue. 

For the integration of your external component (Issue #122), @fgeyer16 can probably assist you best, since the Profiles-server for myclimateservices is needed aswell and I don't have access to that one.

**Comment by ghilbrae** [comment]
We've created a new issue (#134) to describe the outcome of the integration. I think we can close this one and continue working with Issues #122 and #134
