### ISSUE TITLE
What are Study Presets

### ISSUE THREAD

**Issue by ghilbrae** [clarity-h2020/csis#125]
It is not clear what Presets are in a Study. They are not linked to the DP or to external resources, so what should be used this for?

**Comment by patrickkaleta** [comment]
Those study presets, or sometimes called (climate) scenarios, act like a filter. The users define what they are actually interested in (a combination of RCP * Emission scenario * event frequency) and our components then show only the data, layers, etc. that fit this combination (in the map, the table,...).

They are not meant to be immutable. Once a user has set a preset and e.g. created a couple of screenshots, the user can switch to another preset and see how this affects the analyzed study area.

We know that "study preset" is not a self-explaining label, so we're open for other suggestions. We didn't go with "scenario", since that name is already used in other places ("Emission scenario", and also Emikat uses the term "scenario" to describe something else).

**Comment by DenoBeno** [comment]
The idea is that users should be able to define more than one preset in the
future.  Then, all the visualization should be shown exactly for the
presets the user chose.

Typically,  one would define one "past climate " preset and a few presets
for the future.  With and without the adaptation options.

Patrick Kaleta <notifications@github.com> schrieb am Do., 5. Dez. 2019,
10:41:

**Comment by ghilbrae** [comment]
Thanks!
