### ISSUE TITLE
Allow visitors to see (some) studies.

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/csis#130]
On a last meeting, a decision was made to change the permissions for viewing and editing the studies

- [x] Everyone, including the anonymous users should be able to view *some* of the published studies.

For discussion (e,g, @p-a-s-c-a-l):
1. How do we define these "some" studies? Should they simply be able to see all published studies or do we need one more boolean field and logic to generate some?
2. What is it that "everyone" should see? The whole workflow with all steps or just the generated report? We do have a single page with the whole report & pdf export thereof.

By the way, currently the anonymous users can open the study and then see nothing in it. This is definitely not good, we need to add the right rights to all the views involved in presenting the study workflow steps (includign the buttons/menu on top). If the user can't see anything in a step, they should not see the step button.

**Comment by patrickkaleta** [comment]
I guess that's something we could discuss in one of our developer telcos on Mondays. (or maybe even with the others on Tuesdays?)

**Current status:**
Anonymous users can see the general "Study" step" and its tabs - **Introduction, Team, Context, Area, Data, Summary** (Summary without the GL-steps part on the bottom), but they cannot edit or change anything and they also cannot generate the pdf report.
 In addition, they can see in the navigation bar what the next steps would be, but they cannot access them.

> How do we define these "some" studies? Should they simply be able to see all published studies or do we need one more boolean field and logic to generate some?

These "some" studies could be for example all our DC studies. But then we would need yet another boolean field. If we decide to make the GL-steps available to anonymous users, we need to make sure that they won't be able to mess with any of the entities we have there (twins, adaptation options, ...)

> By the way, currently the anonymous users can open the study and then see nothing in it.

If they see nothing then it's because there's nothing in the study (no area selected, no DP selected, no scenario selected,...). Otherwise anonymous users see everything in the Study step just like team members except for the GL-step part of the Summary tab. We could think about adding more to the Study step, but the question is what could that be?

> ...presenting the study workflow steps (includign the buttons/menu on top). If the user can't see anything in a step, they should not see the step button.

We can hide the navigation bar, so that anonymous users won't see things which they cannot access. But that could let them wrongly believe that there is simply nothing more to see and do in a study. By making the nav bar visible, we let them know what they are missing out on by not becoming a registered user on our website.

**Comment by DenoBeno** [comment]
If the anonymous users can see all the steps of the published study but not
change anything (add or remove anything in the report,  I'm happy.

They should IMO be able to play with the maps,  just not save any
screenshots.

Patrick Kaleta <notifications@github.com> schrieb am Fr., 17. Jan. 2020,
11:01:

**Comment by patrickkaleta** [comment]
> If the anonymous users can see all the steps of the published study but not change anything (add or remove anything in the report, I'm happy. 
>
> They should IMO be able to play with the maps, just not save any screenshots.

Alright, so that would put anonymous users basically on the same level as the already defined "observer" group role (see [here](https://github.com/clarity-h2020/csis/issues/114#issue-508910914)). 

I'll update the user/group permissions issue #114 with the new requirements.

**Comment by patrickkaleta** [comment]
I consider this done now. Anonymous users see the list of published studies and can access every step of those studies. They cannot take screenshots, add/remove anything from the studies or generate the final report.

### What has changed:
- the StudyInfo JSON object has now 2 new boolean fields `is_anonymous` and `is_member` to indicate the status of the user viewing the Study. This information is used by the csis-helpers module to hide fields based on custom CSS classes, which can be added to individual fields of the Study group or the GL-steps. That gives us some flexibility in the future if we decide that certain information should stay hidden from non-members or anonymous users.
![hide-fields-by-checking](https://user-images.githubusercontent.com/42167036/73060827-000d2000-3e99-11ea-8fb1-323d9f1d0231.png)
- the group role "**observer**" is now obsolete, since it doesn't offer anything an anymous users can't already do. **Therefore, I suggest to remove this unnecessary role in the near future.**

### One thing to keep in mind:
 Our custom "Make study public" field **only affects whether or not a study is listed on our overviews**. Now that we allowed anonymous users to see everything inside a study, this means that they can view **ALL** studies if they know the right URL. Drupal on its own doesn't offer a way to manage access control based on a custom field value, so we would have to take care of that ourselves if we want this behaviour to change. @DenoBeno any thoughts on that?

**Comment by DenoBeno** [comment]
What observers have on top is that they also can see the unpublished
studies.

**Comment by patrickkaleta** [comment]
> What observers have on top is that they also can see the unpublished studies.

That is now also possible for anonymous users, if the Study owner shares the URL of those unpublished studies. 

IMO people will prefer using this method, since it doesn't require them to create an account on our website, "just so that they can become an observer and not be able to actually do something".

**Comment by p-a-s-c-a-l** [comment]
We have to keep in mind that "Transport Screening" studies like [this one](https://csis.myclimateservice.eu/study/55/step/1952/view/maps) require the user to be logged-in to be able to access the [Transport Application](https://github.com/clarity-h2020/csis/issues/122). So we cannot publish those studies. Or anonymous read-only access has to be implemented in the TA Application. WDYT @ghilbrae ?

The same problem occurs when viewing studies that need access to the EMIKAT API, e.g. via the Map, Table or MCDA Component. See for example [this study](https://csis.myclimateservice.eu/study/35/step/1524/view/table):

![grafik](https://user-images.githubusercontent.com/1788226/73157324-ed852780-40e0-11ea-8cb9-2170c6f76e80.png)

We are are still using [this kind of ugly workaround](https://github.com/clarity-h2020/docker-drupal/issues/16#issuecomment-516717488) for storing EMIKAT credentials which relies on the existence of a user profile. So perhaps it is possible to create an additional read-only anonymous user in EMIKAT @humerh?

**Comment by ghilbrae** [comment]
> We have to keep in mind that "Transport Screening" studies like [this one](https://csis.myclimateservice.eu/study/55/step/1952/view/maps) require the user to be logged-in to be able to access the [Transport Application](https://github.com/clarity-h2020/csis/issues/122). So we cannot publish those studies. Or anonymous read-only access has to be implemented in the TA Application. WDYT @ghilbrae ?

As far as I know, the Transport Module defers to the credentials sent by the CSIS to allow a user to access/see the studies, so in principle there should be no issue. But the best person to answer this would be @rapto who has implemented it.

**Comment by p-a-s-c-a-l** [comment]
Yes, if they are not logged-in (anonymous), users will see the login screen instead:

![grafik](https://user-images.githubusercontent.com/1788226/73173858-9f831a80-4106-11ea-86c4-e5236b44c869.png)

**Comment by luis-meteogrid** [comment]
Right now there is no possibility of anonymous access to the system. If necessary we can incorporate it into the modifications to be made. An alternative, which I don't know if it is possible, would be that when selecting an open transport study, CSIS performs an automatic login with a default user (eg: 'public'); into the Transport Module we can grant this user access in read mode to all the studies. The TM already supports multi-user access

**Comment by p-a-s-c-a-l** [comment]
Do we really want to allow anonymous user to view **all** published studies? Is there a possibility to restrict anonymous access to a small set specific studies we want use to showcase the system?

**Comment by patrickkaleta** [comment]
> Do we really want to allow anonymous user to view **all** published studies?

I'm not a big fan of that idea. Honestly, I would keep the CSIS as restrictive as possible for anonymous users (they still have the marketplace, which is targeting the "broader public") and leave it for more experienced users, who will have an account. 

> Is there a possibility to restrict anonymous access to a small set specific studies we want use to showcase the system?

AFAIK Drupal on it's own does not provide a feature like that. Maybe we could use the [permission by terms](https://www.drupal.org/project/permissions_by_term) module for that purpose. We already use this module for e.g. [managing access to different Study types](https://github.com/clarity-h2020/docker-drupal/issues/115). I'll look into it. 
Otherwise we would have to search for another module or take care of this on our own in the csis-helpers module.

**Comment by ghilbrae** [comment]
We've discussed the issue of the integration of the "anonymous" user view between the CSIS and the TM and we think that the better approach would be to have the CSIS send this configuration to the TM so that the study can be anonymously accessed there too. 

WDYT?

**Comment by p-a-s-c-a-l** [comment]
> Maybe we could use the [permission by terms](https://www.drupal.org/project/permissions_by_term) module for that purpose. We already use this module for e.g. [managing access to different Study types](https://github.com/clarity-h2020/docker-drupal/issues/115). I'll look into it.

O.K. if this is easy to implement, we should go for it. Otherwise we simply unpublish all studies that are not quality assured and guaranteed to work.

**Comment by patrickkaleta** [comment]
> > Maybe we could use the [permission by terms](https://www.drupal.org/project/permissions_by_term) module for that purpose. We already use this module for e.g. [managing access to different Study types](https://github.com/clarity-h2020/docker-drupal/issues/115). I'll look into it.
> 
> O.K. if this is easy to implement, we should go for it. Otherwise we simply unpublish all studies that are not quality assured and guaranteed to work.

Permission by Term module does not work with Studies (because this module doesn't support Groups). So, instead access to Studies is now handled by our CSIS helpers module (I'll update the README of our module ASAP).

Anonymous users can now only access Studies, that have been explicitly allowed by an administrator via the [Configurations](https://csis.myclimateservice.eu/admin/config/csis_helpers/default) of the CSIS helpers module (form can be found in BE: Configuration -> Development -> CSIS module settings). Only those selected Studies will show up in the [list of Available Studies](https://csis.myclimateservice.eu/studies) for anonymous users.

For logged in users nothing changes. They can access Studies, that have been published by the Study owner, as well as all Studies which they are a member of.

| Has access to: | unpublished Study| published Study | "greenlighted" by admin|
| ------------- | ------------- | ------------- | ------------- |
| Anonymous  | ❌   | ❌  | ✔️    |
| Authenticated user (non-member)  | ❌   | ✔️   | ✔️    |
|  Authenticated user (member)  | ✔️    | ✔️    | ✔️    |

**Comment by patrickkaleta** [comment]
I wasn't sure which Studies should ATM be available to anonymous users, so I selected our two advanced screening Studies  [Agios Dimitrios](https://csis.myclimateservice.eu/study/35/view/intro) and [Alba Iulia](https://csis.myclimateservice.eu/study/33/view/intro). As mentioned before, this can now be configured in the CSIS module [settings](https://csis.myclimateservice.eu/admin/config/csis_helpers/default).

Considering this issue now done.
