### ISSUE TITLE
Change the resource description from plain text to formatted text

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/csis#143]
Request form Robert/ZAMG (nice to have)

**Comment by p-a-s-c-a-l** [comment]
IMHO this is needed for https://github.com/clarity-h2020/csis/issues/140

**Comment by patrickkaleta** [comment]
[This](https://www.drupal.org/project/drupal/issues/2843108#comment-12069958) might be what we need to do in order to achieve this. I will test it locally next week.

**Comment by patrickkaleta** [comment]
> [This](https://www.drupal.org/project/drupal/issues/2843108#comment-12069958) might be what we need to do in order to achieve this. I will test it locally next week.

Sadly, that was not what we needed. 

**So, the question is how badly we need this feature?**
In theory, we could just add the original `body` field back to the resources, because it is of type "formatted text" and with a short script (10 lines of code) copy the content of all old `description` fields into the new `body` fields. Problem is that these two fields are not quite the same, so during this "duplication" the current formatting is completely lost. This is the result:
![new description field](https://user-images.githubusercontent.com/42167036/75548653-14ab7d80-5a2e-11ea-831d-821fe468faf8.png)

I would therefore suggest that we add the `body` field back to the DP resources, but leave it empty. If an editor decids that a resource despriptions needs a "fancier" formatting, they can move & change the description field manually.

**Comment by patrickkaleta** [comment]
@RobAndGo FYI, here are the details for the new resource field.

**Comment by patrickkaleta** [comment]
**Proposed change is implemented.** DP resources now have the `body` field (labelled as "Description - formatted"), where descriptions should be entered in from now on. This new fields offers better possibilities to format texts.
