### ISSUE TITLE
Option to create an Advanced Transport Study has disappeared

### ISSUE THREAD

**Issue by ghilbrae** [clarity-h2020/csis#149]
It seems that the option to create a transport study has disappeared:

![image](https://user-images.githubusercontent.com/1615745/76297441-1d1a7880-62b8-11ea-934b-2973c7cb9ae4.png)

Is there anything that's changed here?

**Comment by p-a-s-c-a-l** [comment]
Yes, it has been disabled as described [here](https://github.com/clarity-h2020/docker-drupal/issues/141#issuecomment-590267268). 

@patrickkaleta Is there a possibility to populate this list depending on the role of the user?  IMHO we have to distinguish between expert / non-expert users and/or internal / external users. See also https://github.com/clarity-h2020/docker-drupal/issues/124

**Comment by patrickkaleta** [comment]
> Yes, it has been disabled as described [here](https://github.com/clarity-h2020/docker-drupal/issues/141#issuecomment-590267268).
> 
> @patrickkaleta Is there a possibility to populate this list depending on the role of the user? IMHO we have to distinguish between expert / non-expert users and/or internal / external users. See also [clarity-h2020/docker-drupal#124](https://github.com/clarity-h2020/docker-drupal/issues/124)

Yes, it is possible and already implemented (see [this issue](https://github.com/clarity-h2020/docker-drupal/issues/115)). 

The visibility of different Study types is managed inside the [Study type taxonomy](https://csis.myclimateservice.eu/admin/structure/taxonomy/manage/study_type/overview). On the top of each Study type term under "Permission", it can be configured which user roles should have access to this Study type.

I have given "Editors" access to the "Transport Infrastructure" Study type, so that @ghilbrae can use it for her webinars.
