### ISSUE TITLE
CLARITY Data Package: Exposure Maps Resource specification

### ISSUE THREAD

**Issue by maesbri** [clarity-h2020/csis#15]
This task is responsible for defining the data structure of the Exposure Map(s) that will be included in CLARITY data package. This includes indicating:

how is the resource encoded (e.g., store the information in raster or vector format). Besides, in the case of using vector based data, a set of "standard" attributes must be defined for containing the information, so that all resources of this type have always the same set of attributes (and names) and CLARITY tools can process them in the same manner.
what formats are supported for this specific type of resource (e.g., for raster data: netcdf, geotiff, etc.; for vector data: geojson, shapefile, etc.)
what metadata attributes are used to describe this resource (refer to CLARITY General Data Package specification and https://frictionlessdata.io/specs/data-resource/).
In this task the following partners MUST be involved: METEOGRID/PLINIVS/ZAMG

**Comment by claudiahahn** [comment]
I am not sure if that is the right issue, but Robert mentioned that during the meeting in Frankfurt you have discussed where to find information about the population in cities.

During the meeting in Vienna in January, that was a topic as well and Mattia forwarded a message from Alessandra with an attached PDF. The PDF describes how a population density can be mapped to Urban Atlas polygons (The source of the population data is NSIs and GEOSTAT 2011).  
[jrc103756_uatl_population_jrc_tech_report_alt.pdf](https://github.com/clarity-h2020/csis/files/3260846/jrc103756_uatl_population_jrc_tech_report_alt.pdf)

According to the Copernicus website (https://land.copernicus.eu/news/urban-atlas-update), the population estimates are now already integrated into every polygon within Urban Atlas 2012. I had a look at Urban Atlas for Vienna and Naples. The population information is available. There is just no distinction between age-groups. However, in Table 1 of the attached PDF, they say that age-group data is available for selected countries (Belgium, Spain, Italy, Malta, Netherlands, Slovenia, and UK). One may need to check. However, that could also be a distinction between the screening and the expert studies.

**Comment by p-a-s-c-a-l** [comment]
@claudiahahn Thank you.
@humerh Is population data available in EMIKAT?

**Comment by humerh** [comment]
We have 2 possibilities to get the POPULATION for the required 500mx500m Grid:
1. To use the NEW information in the Urban Atlas data, which contains the population in each polygon
2. To use the 1kmx1km POPULATION Raster from EUROSTAT.

For small polygons the 1st approach is better, for large polygons the 2nd is more exact.

None of these source contains the distribution of age.

I implemented the 2nd approach in EmiKat.
Emikat calculates these data on demand for the Study Area.
This data is available also by REST Interface (and if needed we can also provide a WMS interface)

**Comment by p-a-s-c-a-l** [comment]
@humerh What about the are groups? We need this information for impact calculation.

Would that be a useful resource:
- http://climate.discomap.eea.europa.eu/arcgis/rest/services/UAMV/Percentage_People_75_Or_Older/MapServer
- http://climate.discomap.eea.europa.eu/arcgis/rest/services/UAMV/Percentage_Children_Under_5/MapServer

Source: https://climate-adapt.eea.europa.eu/knowledge/tools/urban-adaptation/Urban-Adaptation-datasets

See also https://eea.maps.arcgis.com/apps/MapSeries/index.html?appid=ec9a942228894562bd53310e3c3bc211

**Comment by p-a-s-c-a-l** [comment]
done

**Comment by p-a-s-c-a-l** [comment]
Some questions to @LauraMTG @luis-meteogrid @ghilbrae @therter @humerh 

- Population Exposure **raw** data (EUROSTAT) is stored on [**METEOGRID** Geoserver](https://clarity.meteogrid.com/geoserver/web/) as layer **geostat_GRID_POPULATION_1K_2011_pers**, then accessed via WCS and processed by EMIKAT and then made available via [EMIKAT Exposure API](https://github.com/clarity-h2020/emikat/issues/10), right?
- this layer does **not** include age groups, we don't need them anyway for the new screening impact model, right?
- This **METEOGRID** Exposure Resource is **not** registered as [Resource in CSIS](https://csis.myclimateservice.eu/maintenance/resources?field_field_eu_gl_methodology_target_id=All&field_resource_tags_target_id=4), therefore cannot be referenced in the [European Data Package](https://csis.myclimateservice.eu/node/682), right?
- The [EE Table Component](https://github.com/clarity-h2020/emikat/issues/10) and the [table-state-rest-api](https://github.com/clarity-h2020/table-state-rest-api/issues/7), respectively, currently access exposure data stored on **METEOGRID** geo server, right? Which layers?
- The EE Table Component / table-state-rest-api is currently broken. Why? Does it need population with age groups which aren't aiable anymore? Did the layer name used by table-state-rest-api change?

So the next step is to create a Population exposure Resource in CSIS pointing to **geostat_GRID_POPULATION_1K_2011_pers** so that we can reference it in studies where **no* *EMIKAT calculation is involved, e.g. *basic screening studies* without impact calculation.

Then try to fix the the table-state-rest-api so that it works again with the new Exposure layer stored on **METEOGRID** Geoserver.

**Comment by therter** [comment]
> The [EE Table Component](https://github.com/clarity-h2020/emikat/issues/10) and the [table-state-rest-api](https://github.com/clarity-h2020/table-state-rest-api/issues/7), respectively, currently access exposure data stored on **METEOGRID** geo server, right? Which layers?

That is right. The following layers are used:

[Exposure:Population_men15_naples](https://csis.myclimateservice.eu/node/427)
[Exposure:Population_15to65_naples](https://csis.myclimateservice.eu/node/434)
[Exposure:Population_mayor65_naples](https://csis.myclimateservice.eu/node/442)
 

> The EE Table Component / table-state-rest-api is currently broken. Why? Does it need population with age groups which aren't aiable anymore? Did the layer name used by table-state-rest-api change?

The EE table works for the [naples data package](https://csis.myclimateservice.eu/node/221), because this data package uses the right exposure layers. See [here](https://csis.myclimateservice.eu/study/1/step/1299/view/table)
The other data packages do not use this layers (and the layers have only data for naples). So the EE table is broken there. 

In contrast to the other tables, the EE table uses the exposure layers from the data package

**Comment by p-a-s-c-a-l** [comment]
New European Exposure data does not include population distribution according to age groups, the three layers for Naples mentioned above are **outdated** and similar layers for other European cities won't be created. The Naples data package includes **outdated** Exposure Layers and has to be updated.

This means that the effort for implementing the exposure table and API was more or less wasted.

**Comment by LauraMTG** [comment]
Hi @p-a-s-c-a-l ,I'll respond as follows:

1- Population Exposure raw data (EUROSTAT) is stored on METEOGRID Geoserver as layer geostat_GRID_POPULATION_1K_2011_pers, then accessed via WCS and processed by EMIKAT and then made available via EMIKAT Exposure API, right?

These are not GEOSTAT raw data, meteogrid has preprocessed the data to convert it to raster and make it available through WCS, as it was necessary.


2- this layer does not include age groups, we don't need them anyway for the new screening impact model, right? 

This is so, the layer does not include age groups.
