### ISSUE TITLE
New users on the CSIS

### ISSUE THREAD

**Issue by ghilbrae** [clarity-h2020/csis#164]
We would like to use *meteogrid* user on csis-dev but we are having trouble login in. It simply does not work. It works on the operational CSIS, though.

We need a new user on the development machine. We are working with some people from the RESCCUE project and we'd like for them to be able to access the CSIS and work on the DP and Study we are creating with their results.

**Comment by p-a-s-c-a-l** [comment]
Did you try to login via https://csis-dev.myclimateservice.eu/user/login ? IMHO SSO is disabled for dev-csis, so you should not login via profiles.myclimateservice.eu. 

Anyway, the user 'meteogrid' exists in DEV instance, so you should be able to login. But it seems [missing the EMIKAT Access credentials](https://github.com/clarity-h2020/docker-drupal/issues/152).

**Comment by ghilbrae** [comment]
Yes, we have tried to log in using that URL and it doesn't work. Could it be possible that the password is different for some reason? @luis-meteogrid

**Comment by patrickkaleta** [comment]
Seems like a lot more users are having issues accessing the DEV instance than previously thought. 

The `meteogrid` user was created about 6 months ago, so probably after the CAS was already in use (@fgeyer16 when was the CAS first used?), so that means this user only has a "CAS password" set, which is of no use now in DEV, since CAS is not active there. @ghilbrae I will reset the password for the meteogrid user on DEV and send you a temporary password via mail, which you can then use to login and afterwards change in your user profile on the DEV instance.

I suggest that we maybe create a separate issue on GitHub collecting all the users who really need access to the DEV instance and then we reset their passwords in order to get rid of this problem.

**Comment by p-a-s-c-a-l** [comment]
resolved
