### ISSUE TITLE
Permissions for creating TM studies

### ISSUE THREAD

**Issue by ghilbrae** [clarity-h2020/csis#165]
We would like to request more users with permissions to create Transport Studies. Currently only the user *angela* can do it and it would be useful to have some others like *meteogrid*.

**Comment by p-a-s-c-a-l** [comment]
I've added the role *editor* to user *meteogrid* on both CSIS instances  **locally**. I did not touch the user managed by CAS on .profile since I'm not authorized to access the user admin page. Note that https://github.com/clarity-h2020/docker-drupal/issues/152 and https://github.com/clarity-h2020/csis/issues/164 have to be resolved first before *meteogrid* can create new TM studies.

**Comment by p-a-s-c-a-l** [comment]
done
