### ISSUE TITLE
Adaptation options for Transport Studies

### ISSUE THREAD

**Issue by ghilbrae** [clarity-h2020/csis#169]
We need to add Adaptation Options for Transport Studies. We already have a list of the AOs. What do we need to do to add them? Do we send you the list or do you prefer to grant us permissions to do it ourselves?

We've noticed that the selection of AOs is related to Urban Studies, so we do not know how our AOs can be taken into account in the current categories. If a new category can be added for the TM it would be interesting being able to choose more than one option.

**Comment by patrickkaleta** [comment]
Well I'm guessing your Adaptation options won't be compatible with the ones we already have from PLENIVS and which are used by Emikat. So, we would need a way to display only the compatible ones depending on the Study type. Using a new category for the AOs could be the way to go.

@ghilbrae please send me the list of the AOs, so that I can see if and how they can be used with our current data model for AOs in the CSIS.  Then we can discuss the next steps.

**Comment by ghilbrae** [comment]
We have compiled the AOs on a User Guide that we have created for the Transport Studies. They are available in Annex 2.

[DC4_guia_uso_csis_saver_transporte_inglés_FINAL_arc.docx](https://github.com/clarity-h2020/csis/files/4877292/DC4_guia_uso_csis_saver_transporte_ingles_FINAL_arc.docx)

**Comment by p-a-s-c-a-l** [comment]
Can we close this issue?

**Comment by patrickkaleta** [comment]
> We have compiled the AOs on a User Guide that we have created for the Transport Studies. They are available in Annex 2.
> 
> [DC4_guia_uso_csis_saver_transporte_inglés_FINAL_arc.docx](https://github.com/clarity-h2020/csis/files/4877292/DC4_guia_uso_csis_saver_transporte_ingles_FINAL_arc.docx)
> 

###This is what we can do
- Looking at your document I see that your AOs are modelled closely to our initial data model proposed for AOs (so just indicators like +, ++, +++ for effects and costs instead of actual values), so **it would be possible to include your AOs in the CSIS**
- In the [AO Identification step](https://csis.myclimateservice.eu/study/55/step/1957/view/table) we would show the initial AO table created by Denis, which would list only those AOs that are included in the data package (for TM Studies that is the DC4 data package, so inside it you would have to add the new AOs first)

> Is it feasible to choose more than one AO?

Yes, following the proposed steps above it would definitely be possible to choose more than just one AO.

###This is what we can get in the end
- we would be able to include AOs to a TM Study and show them in the final PDF report. And that's it, nothing more and nothing less.

###What we won't get
- there will be no calculations performed based on the AOs selected (no cost or impact calculations or similar inside Drupal)
- we won't be able to inform the TM about any AO selections made, since that would require additional implementations for which I don't have the time anymore

@ghilbrae 
So what I can do is to create the necessary View that would list your AOs in the appropriate Step (basically that View already exists thanks to Denis) and include it in the Study template for the TM Studies. In addition I would extend the AO forms with the previous fields we used to include indicators (+, ++, +++,....) instead of actual values, so that you can add AOs into the CSIS. I will need roughly an hour for my tasks, you would have to create the AOs (and possible the Co-benefits and variations on vulnerability as well). In your option: Is the potential outcome of this worth the effort or shall we rather forget about AOs in TM Studies? If you like we can have a short telco regarding this topic today.

**Comment by ghilbrae** [comment]
@patrickkaleta we have discussed this and this approach is perfectly acceptable, we need nothing more and we understand that no calculation will be performed. No problem there.

> So what I can do is to create the necessary View that would list your AOs in the appropriate Step (basically that View already exists thanks to Denis) and include it in the Study template for the TM Studies. In addition I would extend the AO forms with the previous fields we used to include indicators (+, ++, +++,....) instead of actual values, so that you can add AOs into the CSIS. I will need roughly an hour for my tasks, you would have to create the AOs (and possible the Co-benefits and variations on vulnerability as well). **In your option: Is the potential outcome of this worth the effort or shall we rather forget about AOs in TM Studies? If you like we can have a short telco regarding this topic today.**

After discussing the issue with @luis-meteogrid we think it is worth the effort. As such we will upload the AO in the Data Package as soon as possible.

**Comment by patrickkaleta** [comment]
> @patrickkaleta we have discussed this and this approach is perfectly acceptable, we need nothing more and we understand that no calculation will be performed. No problem there.
> 
> > So what I can do is to create the necessary View that would list your AOs in the appropriate Step (basically that View already exists thanks to Denis) and include it in the Study template for the TM Studies. In addition I would extend the AO forms with the previous fields we used to include indicators (+, ++, +++,....) instead of actual values, so that you can add AOs into the CSIS. I will need roughly an hour for my tasks, you would have to create the AOs (and possible the Co-benefits and variations on vulnerability as well). **In your option: Is the potential outcome of this worth the effort or shall we rather forget about AOs in TM Studies? If you like we can have a short telco regarding this topic today.**
> 
> After discussing the issue with @luis-meteogrid we think it is worth the effort. As such we will upload the AO in the Data Package as soon as possible.

Perfect! I will adapt the form for creating new AOs to fit your needs and give you a more detailed description on how to add the AOs you've created.

**Comment by patrickkaleta** [comment]
To create new Adaptation options fitting your needs please use this form: https://csis-dev.myclimateservice.eu/node/add/adaptation_options/ao_simplified

ATM there is no dedicated button to get to this AO form, I will change that later, but for now just use the link above. The default AO form will not suit your needs, since it will ask for concrete numbers for development and retrofitting costs.

This form should provide you with all the fields necessary to create AOs as described in Annex 2. The column "Towards which hazard" and "Variation on vulnerability of element at risk" are combined in the `Add existing Vulnerbility change` field. Non existant vulnerability changes can be added directly via the "Add effect" button inside the "Select effects" pop-up window.

Non existant Co-benefits have to be added before the actual AO is created. That can be done [here](https://csis-dev.myclimateservice.eu/admin/structure/taxonomy/manage/co_benefits/overview).

**Comment by patrickkaleta** [comment]
How is it going with the AOs for the TM studies @ghilbrae? Are you ready to include them in the data package?

**Comment by ghilbrae** [comment]
I've tried adding one (https://csis-dev.myclimateservice.eu/node/5187) and it seems to show just right in the DP (https://csis-dev.myclimateservice.eu/node/705). I've yet to see how this looks from a Study.

**Comment by patrickkaleta** [comment]
> I've tried adding one (https://csis-dev.myclimateservice.eu/node/5187) and it seems to show just right in the DP (https://csis-dev.myclimateservice.eu/node/705). I've yet to see how this looks from a Study.

You can see it here in [this Study](https://csis-dev.myclimateservice.eu/study/177/step/5368/view/table). Seems to be working just fine.

**Comment by DenoBeno** [comment]
If you need to find out which AOs are chosen in the study from the outside,  I am sure this is possible using the drupal rest interface.

**Comment by p-a-s-c-a-l** [comment]
done
