### ISSUE TITLE
Update Texts for Transport Studies

### ISSUE THREAD

**Issue by ghilbrae** [clarity-h2020/csis#171]
We already have the new versions for the texts for the Transport Studies. Do we send them to you or do you want us to change them ourselves? As discussed on Monday, we have no problem changing the templates if you point out to us where and how.

**Comment by patrickkaleta** [comment]
@ghilbrae can you tell me where exactly you want to update the texts? Is it in the Study-section or inside the individual GL-steps? Depending on that you would have to change the texts in different locations. I would then show you were exactly they can be changed and make sure that you have the necessary permissions to do so.

**Comment by ghilbrae** [comment]
@patrickkaleta for now we just need to change the texts in Vulnerability but, as we are working with users right now, we may need to change others at some other time.

**Comment by patrickkaleta** [comment]
To change the introduction texts for TM Studies in general, just edit the appropriate GL-step template inside the [StudyType taxonomy](https://csis-dev.myclimateservice.eu/taxonomy/term/3895/edit?destination=/admin/structure/taxonomy/manage/study_type/overview). **Note: That will only affect all TM Studies that are created after that point. Existing TM Studies will not be affected**

**1)** Scroll down to the **STUDY STEPS** section and click the Edit button for the Step that you want to change
![step-1](https://user-images.githubusercontent.com/42167036/87278268-507a4780-c4e4-11ea-9e1c-b8bcca0ddeb4.png)

**2)** The form of the GL-step template pops up and in there find the **Step description** field. There you can make your changes.
![step-2](https://user-images.githubusercontent.com/42167036/87278274-52440b00-c4e4-11ea-9880-63deb91ac6fa.png)


**3)** When you're down the the GL-step scroll down a bit until you see the **Update GL step Template** button. You need to click that, so that your changes will be imported.
**4)** Once you're done with all the GL-Steps you needed to update, click the **Save** button at the bottom to save your updates.

**Comment by patrickkaleta** [comment]
If you want to change the texts of existing TM Studies, you will have to do this one by one. For that just visit the GL-Step in question and click on the **Change description** button on the bottom.
