### ISSUE TITLE
Table view in "Hazard characterization" step.

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/csis#172]
Could someone please enlighten me concerning this page? It's in Hazard characterization, where we have tons of indices and where (as I just learned), the event frequency is not represented in the hazard data. 

And yet, only two data sets are shown on https://csis.myclimateservice.eu/study/37/step/1640/view/table and they do reference period, rcp scenario and event frequency. and what is shown changes, depending on the scenario chosen... So what exactly is shown here and how is it related to hazard layers that we show?

**Comment by RobAndGo** [comment]
I can explain.

Note that in the presentation, the heat index showing the temperature during a 7-day heat wave is a **user-friendly** version of what is shown in the table. This was only produced within the last weeks, and so was not uploaded into CSIS. And I think Meteogrid (@ghilbrae and @LauraMTG) are busy with other more important things than to deal with yet another dataset.

Originally, the heat index value in the table was only planned to be used for calculations in emikat for the PLINVIS local model, and so was not going to be shown to the public. This is why the value of "0.066 days at 41C" is so cryptic.

**Comment by p-a-s-c-a-l** [comment]
The HC Table is not related to hazard layers show in the map at all.

Let me explain: New [simple tables](https://github.com/clarity-h2020/simple-table-component) are fed by **EMIKAT APIs** only, not HC datasets stored on GeoServer. Reason is that after changes in data structure and due to lack of resources for re-implementing the aggregation we had to abandon the old [table-components(https://github.com/clarity-h2020/table-components) (CIS) and especially the [table-state-rest-api](https://github.com/clarity-h2020/table-state-rest-api) (METEOGRID) which was responsible for data aggregation. 

We could probably try to implement tables that show hazard indexes from geo server, but without aggregation and such, just showing the plain data as it is. But before that, we introduce kind of split-tables for comparing baseine vs. adapted scenariosn as [we intend to implement for the maps](https://github.com/clarity-h2020/map-component/issues/100).

Why does the table just shortwo ~~datasets~~ rows? -> This was changed by [request](https://github.com/clarity-h2020/csis-technical-validation/issues/53#issuecomment-648810912).

> This is why the value of "0.066 days at 41C" is so cryptic.

The original data retrieved from EMIKAT is even more cryptic: `35.5_0.066d`

> I originally planned to enter the "user-friendly" version of the data into the data package,

Since the tables retrieve their data from EMIKAT, it has to be there stored there too.

**Comment by RobAndGo** [comment]
Indeed the 35.5_0.066d is cryptic ![laugh](https://user-images.githubusercontent.com/45385637/86475679-6b5ef600-bd45-11ea-8bc4-5b3b29a207e4.gif) - here my thought was that it would be easy to write a script which splits this quantity at the delimiter _ to extract the two pieces of information.
But I was referring to having such a **small fraction of a day** (0.066d) count as a "heat wave". This is necessary for the calculation, but really does not mean anything to anyone else.
