### ISSUE TITLE
Calculation can't be triggered on test instance of CSIS

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/csis#175]
I suppose this is meant as a feature, but now I can't test the updated screening workflow because I can't trigger the calculation. How is this supposed to work?

**Comment by DenoBeno** [comment]
I have entered one EMIKAT ID from an existing study and now I can see how the new study looks like, I just can't trigger anything new.

**Comment by patrickkaleta** [comment]
> I suppose this is meant as a feature

Exactly, it's a safety precaution. It's not possible to trigger Emikat from the DEV instance, so that it doesn't interfere with the "real version" of the Study on PROD. 
E.g. someone mistakenly edits the Study on DEV (changes Area or Adaptation option or whatever) and runs the calculation again. PROD would then only seemingly show Emikat results for the selected settings on PROD, when in reality it was using the settings configured on DEV.
