### ISSUE TITLE
European Transport Studies do not connect with the TM

### ISSUE THREAD

**Issue by ghilbrae** [clarity-h2020/csis#189]
Hi!
We have been testing the creation of Transport European studies and we noticed that there is a problem between the CSIS and the TM. We do not know if this is on the CSIS side or in the TM side but it seemed that the study was not being created in the TM side. 

BTW, we were working on the development instance.

**Comment by patrickkaleta** [comment]
> BTW, we were working on the development instance.

Most likely the reason why these Studies did not show up in your system. AFAIK we use the Study IDs as unique identifiers for our communication between CSIS and TM and for example Study 25 is something different on DEV than it is on PROD, so saving that Study on DEV could then unintentionally overwrite the actual Study 25 from PROD inside the TM.

But I'll look into. I know that for Emikat we definitely don't allow the DEV instance to send anything. For the TM Studies I need to double-check.

**Comment by patrickkaleta** [comment]
Yes, it's just like I thought. We use the Study IDs as unique identifiers and that's why the communication between CSIS DEV and the TM is forbidden.

E.g. your test TM study 189 on DEV could've potentially overwritten an already existing TM Study 189, which was sent to the TM previously from the PROD instance of the CSIS. Or (depending on how this is implemented on the TM side) the request from DEV would've been rejected because the ID 189 was already in use. Either way, with the current setup we simply cannot allow the TM to communicate with PROD and DEV simultaneously.

**Comment by ghilbrae** [comment]
Ok, so there's no problem on either side. Good to know and thanks for clarifying.

I'll close the issue then.

**Comment by patrickkaleta** [comment]
Seems like now we have a real issue with the connection.

Currently, when the CSIS tries to send a new Study to the TM, we receive the following error response from the TM:

`Server error: POST https://clarity.saver.red/es/simmer/api/study/ resulted in a 500 Internal Server Error response: IntegrityError at /es/simmer/api/study/ null value in column "user_id" violates not-null constraint DETAIL: Failing row (truncated...)`

Has the configuration in the TM been changed lately? Does it expect other parameters now @ghilbrae @rapto?

**Comment by rapto** [comment]
Hello there. I have tried this:
```
http --debug -j POST https://clarity.saver.red/es/simmer/api/study/  "Authorization:Token xxxxxxxxxxxxxxxxx" simulationtype=158 users:='["meteogrid"]'
```
and it seems to work. What is it that you tried?
