### ISSUE TITLE
CSIS Permissions to create Data Package

### ISSUE THREAD

**Issue by ghilbrae** [clarity-h2020/csis#62]
Hi! We are stating with the DC4 Data Package but our(my) user does not have permissions to edito or create one. The user we are using at Meteogrid rn is the one I have (username: angela). Could someone give this account permissions to do that?

Thanks!!

**Comment by p-a-s-c-a-l** [comment]
I assigned the role 'editor' to the user 'angela'. HTH.

**Comment by ghilbrae** [comment]
Thanks!

**Comment by maesbri** [comment]
Hi,

I just accessed today the csis as I wanted to update the Naples data package but it seems now that my account has no permissions to edit anymore resources and/or data packages!

![image](https://user-images.githubusercontent.com/9677881/64013473-2dd77e00-cb20-11e9-896e-52f2597c1df8.png)

**Comment by fgeyer16** [comment]
Looks like you are in the system twice once as miguel.esbri who is administrator and once as miguel.esbri@atos.net who is only authenticated user and who was created by CAS. Second has no permission to edit data packages and resources. 
I wanted to change role of second so he is able to work, but both Miguels have the same email address and so I can not save them anymore. Options:

- delete miguel.esbri@atos.net
- give one of the both another email address

let me know which one I shall do.

miguel.esbri can only log in locally (/user/login entered manually in the address bar of the browser use not the login link in the menu) because he is an admin and I do not want to allow admins SSO.

**Comment by maesbri** [comment]
ok, I wasn't aware of that ..., then I think it is better if you just delete miguel.esbri@atos.net account.
Thank you very much!

**Comment by fgeyer16** [comment]
Deleted the miguel.esbri@atos.net account.
