### ISSUE TITLE
Hide the sub-steps if there is nothing to show.

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/csis#81]
We have a mechanism for defining templates for different study types in place now. If a GL-STEP step isn't defined at all, it is also not shown in the study. 

However, all the sub-steps are always shown, even if there is nothing to see. This needs to be fixed.

**Comment by DenoBeno** [comment]
Has this been implemented? The other day, I thought that I saw some sub-steps disappearing. Maybe they disappear when included view is broken?

**Comment by patrickkaleta** [comment]
Most of the logic is handled inside the [view](https://csis.myclimateservice.eu/admin/structure/views/view/study_group_tab_for_content/edit/block_1) that is responsible for the tabs (or "sub-steps" if you like). In the past we had some special exceptions, where in certain steps additional tabs where needed unique to only that specific step, that's why those exceptions where created inside the view logic. 

I will make this more uniform across all the steps and tabs (aka sub-steps) ASAP.

**Comment by patrickkaleta** [comment]
I updated the logic for the sub-steps (tabs). **Tabs are now displayed/hidden based on whether or not the respective field is set in the GL-Step** (exception is "Data" tab, explained below).

**Before these updates the logic for the tabs looked like this:**
- **Introduction** - shown always
- **Data** - shown in all EU-GL Steps except AO Identification
- **Table** - shown always
- **Maps** - shown in all steps except VA and AO Identification
- **Twins** - only if field was set in the GL-Step
- **Scenario Analysis** - only shown in step RIA 

**Some clarifications:**
- displayed/hidden EU-GL steps (HC, VA, ...) depend on the entity type GL-Step, while the shown/hidden sub-steps (Introduction, Table, Maps, ...) depend (mostly) on individual fields of a GL-step --> that's why the logic differs and those two things are handled by two different views  
- the "Data" tab is, unlike the others, created by an EVA view, so I cannot simply check whether a certain field in the GL-step is set. Until now the view was configured to show the "Data" tab on all steps except the AO Identification. **I left that behaviour unchanged**.
- as requested [here](https://github.com/clarity-h2020/docker-drupal/issues/99#issuecomment-524217032), I also completely disabled the "Scenario analysis" tab inside the view, since this is less work than going through all GL-templates and individual GL-steps to unset the `Embed: Scenario Analysis Application` field and later set it again once the app is working

I'm considering this done, therefore closing this issue now.

**Comment by DenoBeno** [comment]
Just a warning for the future: don't expand the fields if you only need to
check if they exist. It's costly.

**Comment by p-a-s-c-a-l** [comment]
Two questions: 
- How can I enable the  "Scenario analysis" again once the app is fixed
- GL step contains `field_external_app`. Where should this be shown? O m a separate tab. I configured it [here]https://csis.myclimateservice.eu/study/35/step/1450/view/introduction), but it isn't shown anywhere.

**Comment by patrickkaleta** [comment]
> Two questions:
> 
> * How can I enable the  "Scenario analysis" again once the app is fixed

In this [view](https://csis.myclimateservice.eu/admin/structure/views/view/study_group_tab_for_content/edit/block_1) the `Tab-links` field takes care of creating the individual tabs. The "Scenario Analysis" is currently commented out with `{# #}`. Removing that will enable this tab if the `field_scenario_analysis_applicat` is set.
> * GL step contains `field_external_app`. Where should this be shown? O m a separate tab. I configured it [here](https://csis.myclimateservice.eu/study/35/step/1450/view/introduction), but it isn't shown anywhere.

A good question. Currently it is not included in any of the [GL-step display modes](https://csis.myclimateservice.eu/admin/structure/types/manage/gl_step/display), so it's never shown. We could either
**(1)** create a completely new tab for external apps (call it: **External, Others, Various, Extras**,...?) 
**(2)** or add it to one of the existing tabs (probably **Table** or **Maps**) and adjust the above mentioned view accordingly

For now, I would probably prefer the 2. option. @DenoBeno any other suggestions?

**Comment by p-a-s-c-a-l** [comment]
> A good question. Currently it is not included in any of the [GL-step display modes](https://csis.myclimateservice.eu/admin/structure/types/manage/gl_step/display), so it's never shown. We could either
> **(1)** create a completely new tab for external apps (call it: **External, Others, Various, Extras**,...?)
> **(2)** or add it to one of the existing tabs (probably **Table** or **Maps**) and adjust the above mentioned view accordingly

I'm in favour of option (1) because those apps are neither maps nor tables. Furthermore, the "Include in Report" Button [for iFrames](https://github.com/clarity-h2020/csis-helpers-module/issues/13) supports ATM only one iFrame per page.

**Comment by patrickkaleta** [comment]
> > A good question. Currently it is not included in any of the [GL-step display modes](https://csis.myclimateservice.eu/admin/structure/types/manage/gl_step/display), so it's never shown. We could either
> > **(1)** create a completely new tab for external apps (call it: **External, Others, Various, Extras**,...?)
> > **(2)** or add it to one of the existing tabs (probably **Table** or **Maps**) and adjust the above mentioned view accordingly
> 
> I'm in favour of option (1) because those apps are neither maps nor tables. Furthermore, the "Include in Report" Button [for iFrames](https://github.com/clarity-h2020/csis-helpers-module/issues/13) supports ATM only one iFrame per page.

I see... good, I will add an additional Tab (let's call it **"External"** or do you have a better name?). In theory this shouldn't be much work. Should be done and ready tomorrow.

**Comment by patrickkaleta** [comment]
I've added an **External** tab, which is shown if the GL-step has the `field_external_app` set. Example here: https://csis.myclimateservice.eu/study/35/step/1525/view/external

I've positioned this tab between the **Maps** and **Twins** tab, but this can be changed if necessary.

ATM taking screenshots is not working for those external apps. I will report more on that in #60.
